CAL-1339 - Data Explorer fix and Pagination
OakCityLabs/callisto-r pull request #6
Opened 2023-03-29 16:14 UTC by kyle-norris

2023-03-31 15:34 UTC, pyb4430 commented on R/vars_manager.R
> +            i <- i + 1
can this be combined with the for loop on line 233?

2023-03-31 21:45 UTC, pyb4430 commented on R/vars_manager.R
> +                row_names[i] <- as.character(i)
I don't think this is quite right, `row_names` should match the page you're delivering (`start` to `end`)

2023-03-31 21:47 UTC, pyb4430 commented on R/vars_manager.R
> +            i <- i + 1
same concern as above, this doesn't account for the page offset, the row_names should match the page you're on

2023-03-31 21:48 UTC, pyb4430 commented on R/vars_manager.R
> +            }
same as above, if there's no specific rownames then the row_names should reflect the page you're on

2023-03-31 21:49 UTC, pyb4430 requested changes
some row_names concerns, doesn't match callisto-python behavior

2023-04-04 12:04 UTC, kyle-norris commented
you're definitely right about those row_names, they should be fixed now 👍

2023-04-05 19:25 UTC, pyb4430 approved these changes

2023-04-06 10:23 UTC, merged